require 'pry'

user1 = User.create(name: "Sam", personality_id: 16)
User.create(name: "Dustin")
User.create(name: "Michelle")
User.create(name: "Tanzima")

Personality.create(name: "INTJ")
Personality.create(name: "INTP")
Personality.create(name: "ENTJ")
Personality.create(name: "ENTP")
Personality.create(name: "INFJ")
Personality.create(name: "INFP")
Personality.create(name: "ENFJ")
Personality.create(name: "ENFP")
Personality.create(name: "ISTJ")
Personality.create(name: "ISFJ")
Personality.create(name: "ESTJ")
Personality.create(name: "ESFJ")
Personality.create(name: "ISTP")
Personality.create(name: "ISFP")
Personality.create(name: "ESTP")
Personality.create(name: "ESFP")

Meme.create(name: "the most attractive, smartest, perfect individual envied by the entire world.", personality_id:1, url:"https://i.imgur.com/3AuqZwb.jpg")
Meme.create(name: "Professor", personality_id:2, url: "https://i.imgur.com/jJPSWUa.jpg")
Meme.create(name: "the Commander", personality_id:3, url: "https://i.imgur.com/HCrpP8H.jpg")
Meme.create(name: "the Debater", personality_id:4, url:"https://i.imgur.com/7Dr0fV5.jpg")
Meme.create(name: "the QT Pie", personality_id:5, url:"https://i.imgur.com/KF0yNsa.jpg")
Meme.create(name: "the Mediator", personality_id:6, url:"https://i.imgur.com/rOsiAEP.jpg")
Meme.create(name: "the Humble Bragger", personality_id:7, url:"https://i.imgur.com/ILl8ydB.gif")
Meme.create(name: "the Campaigner", personality_id:8, url:"https://i.imgur.com/vBnCQoV.jpg")
Meme.create(name: "the Deep Thinker", personality_id:9, url:"https://i.imgur.com/SvG7gbW.png")
Meme.create(name: "the Struggler", personality_id:10, url: "https://i.imgur.com/nVUuTeA.jpg")
Meme.create(name: "DA BOSS", personality_id:11, url:"https://i.imgur.com/uuYdpIT.jpg")
Meme.create(name: "the Tea Drinker", personality_id:12, url:"https://i.imgur.com/cnAT15M.jpg")
Meme.create(name: "the Golden Bruno", personality_id:13, url: "https://i.imgur.com/YSXYZRU.png")
Meme.create(name: "the Adventurer", personality_id:14, url:"https://i.imgur.com/7jLhzbW.png")
Meme.create(name: "the Logical Thinker", personality_id:15, url:"https://i.imgur.com/a6UZdpn.jpg")
Meme.create(name: "Paul Minaj", personality_id:16, url:"https://i.imgur.com/gm5uof2.jpg")

puts "lol"
